apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels: 
    type: api
spec:
  template:
    metadata: 
      name: api-pod
      labels:
        type: api
    spec:
      containers:
        - name: api-container
          image: ghcr.io/sumanthmysore/voteapp-be:randomtag
          imagePullPolicy: Always
          env:
          - name: MONGO_CONN_STR
            value: "mongodb://admin:password@mongo-0.mongo-svc,mongo-1.mongo-svc,mongo-2.mongo-svc:27017/langdb"
      imagePullSecrets:
        - name: ghcr-secret 
  replicas: 4
  selector:
    matchLabels:
      type: api