imageTag: latest

deployments:

  - kind: Deployment
    deploymentName: fe-deployment
    imageName: ghcr.io/sumanthmysore/voteapp-fe
    pullPolicy: Always
    replicas: 4
    imagePullSecret: ghcr-secret
    label: fe
    containerName: fe-container
    podName: fe-pod

  - kind: Deployment
    deploymentName: api-deployment
    imageName: ghcr.io/sumanthmysore/voteapp-be
    pullPolicy: Always
    replicas: 4
    imagePullSecret: ghcr-secret
    label: api
    containerName: api-container
    podName: api-pod
    env: 
      name: MONGO_CONN_STR
      value: "mongodb://admin:password@voteapp-release-db-deployment-0.db-service,voteapp-release-db-deployment-1.db-service,voteapp-release-db-deployment-2.db-service:27017/langdb"

  - kind: StatefulSet
    deploymentName: db-deployment
    imageName: ghcr.io/sumanthmysore/voteapp-db
    imageTag: latest
    pullPolicy: Always
    replicas: 4
    imagePullSecret: ghcr-secret
    label: db
    containerName: db-container
    podName: db-pod
    serviceName: db-service

services:

  - serviceName: fe-service
    label: fe
    type: ClusterIP
    port: 80
    targetPort: 80

  - serviceName: api-service
    label: api
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  - serviceName: db-service
    label: db
    port: 27017
    targetPort: 27017
