deployments:

  - kind: Deployment
    deploymentName: fe-deployment
    imageName: ghcr.io/sumanthmysore/voteapp-fe
    imageTag: latest
    pullPolicy: Always
    replicas: 4
    imagePullSecret: ghcr-secret
    label:
      type: fe
    containerName: fe-container
    podName: fe-pod

  - kind: Deployment
    deploymentName: api-deployment
    imageName: ghcr.io/sumanthmysore/voteapp-be
    imageTag: latest
    pullPolicy: Always
    replicas: 4
    imagePullSecret: ghcr-secret
    label:
      type: api
    containerName: api-container
    podName: api-pod
    env: 
      name: MONGO_CONN_STR
      value: "mongodb://admin:password@mongo-0.mongo-svc,mongo-1.mongo-svc,mongo-2.mongo-svc:27017/langdb"

  - kind: StatefulSet
    deploymentName: db-deployment
    imageName: ghcr.io/sumanthmysore/voteapp-db
    imageTag: latest
    pullPolicy: Always
    replicas: 4
    imagePullSecret: ghcr-secret
    label:
      type: db
    containerName: db-container
    podName: db-pod
    serviceName: db-service

services:

  - serviceName: fe-service
    label:
      type: fe
    type: ClusterIP
    port: 80
    targetPort: 80

  - serviceName: api-service
    label:
      type: api
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  - serviceName: db-service
    label:
      type: db
    port: 27017
    targetPort: 27017
