{{- range .Values.deployments }}
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ $.Release.Name }}-{{ .deploymentName }}
  labels: 
    type: {{ .label }}
spec:
  template:
    metadata: 
      name: {{ .podName }}
      labels:
        type: {{ .label }}
    spec:
      containers:
        - name: {{ .containerName }}
          image: {{ .imageName }}:{{ $.imageTag }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- if .env }}
          env:
            - name: {{ .env.name }}
              value: {{ .env.value }}
          {{- end }}
      imagePullSecrets:
        - name: {{ .imagePullSecret }}
  replicas: {{ .replicas }}
  {{- if .serviceName }}
  serviceName: {{ .serviceName }}
  {{- end }}
  selector:
    matchLabels:
      type: {{ .label }}
---
{{- end }}
