apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels: 
    type: fe
spec:
  template:
    metadata: 
      name: fe-pod
      labels:
        type: fe
    spec:
      containers:
        - name: fe-container
          image: {{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret  
  replicas: 4
  selector:
    matchLabels:
      type: fe