{{- range .Values.services  }}
apiVersion: v1
kind: Service
metadata: 
  name: {{ .serviceName }}
  labels:
    type: {{ .label }}
spec:
  {{- if .type  }}
  type: {{ .type }}
  {{- else }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  selector:
    type: {{ .label }}
---
{{- end }}